version: '3.9'

services:
  DB:
    container_name: database
    image: mysql
    restart: on-failure
    networks:
      sql:
        aliases:
          - Mysql
    ports:
      - "3007:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: misnovelas
    logging:
      driver: none
    volumes:
      - ./schemas:/var/lib/mysql:rw
  Novelas:
    networks:
      sql:
        aliases:
          - Apk
    depends_on:
      - DB
    restart: always
    container_name: Novelas
    image: novelas
    build: .
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    entrypoint: ["./wait-for-it.sh","Mysql:3007","--","npm","run","dev"]
    # command:  ["npm","run","dev"]
   
volumes:
  schemas: {}

networks:
  sql:
    name: Novelas
    driver: bridge
    ipam:
      driver: default
